* Long-only trading portfolio across five equity indices
The exercise entails the development of a long-only trading model, the output of which will be a portfolio weight matrix across five equity indices.
Each candidate will be provided with a dataset containing:

** Dataset

 - Five historical series of daily logarithmic returns pertaining to stock indices from five different geographic regions.
 - Six historical series of Fundamental Indicators for each stock index.
 - Two historical series of daily logarithmic returns related to interest rates for each geographic area.
 - Two historical series of Macroeconomic Indicators for each geographic area.
 - Three historical series of daily logarithmic returns related to currency crosses.
 - Three historical series of daily logarithmic returns related to commodities.
 - The resulting portfolios should exclusively comprise a combination of weights of these five stock indices.

The data is available in *data/data.xlsx*

** Task requirements and evaluation
The in-sample period spans from September 30, 2003, to December 31, 2019.

Out-of-sample results and the scientific rigor of the model will be the primary criteria for evaluation.

Materials that enhance clarity, comprehensibility, and readability of the model will be highly regarded.

This includes, but is not limited to, the formalization of the model using LaTeX or similar typesetting systems,
detailed and clear code comments, and self-explanatory variable nomenclature to the greatest extent possible.

The model must be implemented using Python, and candidates may employ any libraries or tools at their disposal.

* Python versions and dependencies:

       1. *pandas* & *openpyxl* (main data management module using pandas.DataFrame)
       2. *matplotlib* (for plotting stuff)
       3. *numpy* (linear algebra calculations)
       4. *scipy* (optimization algorithms)
       5. *scikit-learn* (linear regression, PCA, model selection through scoring)
       6. *seaborn*
	  
Python versions: /python3.11/ or /python3.12/

* Code structure and how to use!

Basically just run *run.py* and choose/uncomment out what you dont need.

* Useful links, tips and notes:

1. install python module on Windows: python3.11.exe -m pip install /module_name/
2. Scikit-learn docs: https://scikit-learn.org/stable/
3. something: https://www.math.hkust.edu.hk/~makchen/MAFS5140/Chap3.
4. huge machine learning library: https://scikit-learn.org/stable/
5. this one is good too: https://www.statsmodels.org/stable/index.html

* TODO Todo list per module [0/0]
  + model.py
    + [-] fix structure linear_regression_model_train -> model_train -> run
    + [-] check print statements and loggin statements
    + [-] print portfolio weight matrix based on chosen timeperiod
    + [-] histogram plot of residuals
    + [-] check rolling window dates
    + [-] check variable naming and comments
    + [-] make func for plotting the portfolio and stocks return with highlight
      + also fix resampling for timeframes other than daily
