* Long-only trading portfolio across five equity indices
The exercise entails the development of a long-only trading model, the output of which will be a portfolio weight matrix across five equity indices.
Each candidate will be provided with a dataset containing:

** Dataset

 - Five historical series of daily logarithmic returns pertaining to stock indices from five different geographic regions.
 - Six historical series of Fundamental Indicators for each stock index.
 - Two historical series of daily logarithmic returns related to interest rates for each geographic area.
 - Two historical series of Macroeconomic Indicators for each geographic area.
 - Three historical series of daily logarithmic returns related to currency crosses.
 - Three historical series of daily logarithmic returns related to commodities.
 - The resulting portfolios should exclusively comprise a combination of weights of these five stock indices.

The data is available in *data/data.xlsx*.

** Task requirements and evaluation
The in-sample period spans from September 30, 2003, to December 31, 2019.

Out-of-sample results and the scientific rigor of the model will be the primary criteria for evaluation.

Materials that enhance clarity, comprehensibility, and readability of the model will be highly regarded.

This includes, but is not limited to, the formalization of the model using LaTeX or similar typesetting systems,
detailed and clear code comments, and self-explanatory variable nomenclature to the greatest extent possible.

The model must be implemented using Python, and candidates may employ any libraries or tools at their disposal.

* Python versions and dependencies:
       + *pandas* & *openpyxl* :: main data management module using pandas.DataFrame
       + *matplotlib* :: for plotting stuff
       + *numpy* :: linear algebra calculations
       + *scipy* :: optimization algorithms
       + *scikit-learn* :: linear regression, PCA, model selection through scoring
       + *seaborn* :: for statistical visualization (heatmap)
	  
Python versions: /python3.11/ or /python3.12/

* How to use
#+BEGIN_SRC shell
  git clone --depth=1 https://github.com/Mediacom99/quant-research.git
#+END_SRC
First install the necessary python packages for the chosen version of python (or use shell.nix),
then run the following commands
#+BEGIN_SRC shell
  cd src
  python run.py
#+END_SRC
Then you can decide what function calls to comment/uncomment in run.py for cleaning the data,
exploratory analysis or running the model and optimizing the portfolio.

* Code structure
- clean_data.py :: cleaning the data
- eda.py :: exploratory data analysis
- model.py :: PCA and linear multifactor model
- optimize.py :: porfolio optimization using risk-parity
- run.py :: entry point

* Useful links, tips and notes:
+ install python module on Windows: python3.11.exe -m pip install /module_name/
+ Scikit-learn docs: https://scikit-learn.org/stable/
+ something: https://www.math.hkust.edu.hk/~makchen/MAFS5140/Chap3.
+ huge machine learning library: https://scikit-learn.org/stable/
+ this one is good too: https://www.statsmodels.org/stable/index.html

# Ctrl-C Ctrl-C to toggle the checkboxes
* TODO Todo [0%]
  + [ ] model.py [0/7]
    + [ ] fix structure linear_regression_model_train -> model_train -> run
    + [ ] check print statements and loggin statements
    + [ ] print portfolio weight matrix based on chosen timeperiod
    + [ ] histogram plot of residuals
    + [ ] check rolling window dates
    + [ ] check variable naming and comments
    + [ ] make func for plotting the portfolio and stocks return with highlight
          also fix resampling for timeframes other than daily
  + [ ] eda.py [0/1]
    + [ ] check stock cumulative returns graph  
	  
      
